### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by chenruizhe1998** [chachae/OES#3]
请问你这里有前端代码吗？

**Comment by chachae** [comment]
> 请问你这里有前端代码吗？

系统使用传统的MVC实现方式，没有前后端分离，视图层具体代码在oes-core模块下的 templates 内

**Comment by chenruizhe1998** [comment]
请问，如果我要修改连接数据库的一些信息，我在哪里可以改？

**Comment by chachae** [comment]
> 请问，如果我要修改连接数据库的一些信息，我在哪里可以改？
https://github.com/chachae/Online-Testing-Platform/blob/master/oes-core/src/main/resources/config/application-prod.yml

**Comment by chachae** [comment]
> 请问，如果我要修改连接数据库的一些信息，我在哪里可以改？

https://github.com/chachae/Online-Testing-Platform/blob/master/oes-core/src/main/resources/config/application-prod.yml

**Comment by chachae** [comment]
> 请问，如果我要修改连接数据库的一些信息，我在哪里可以改？

https://github.com/chachae/Online-Testing-Platform/blob/master/oes-core/src/main/resources/config/application-prod.yml

**Comment by Bbeginner** [comment]
请问这个项目测试的账户名,密码是什么，数据库里面的密码是加密的吧？
